In [1]:
!pip install numpy
import numpy as np


In [2]:
d = np.array([[1,2,3]],np.int32)

In [3]:
print(d)

[[1 2 3]]


In [4]:
d[0,1]

2

In [5]:
d.shape

(1, 3)

In [6]:
d.dtype

dtype('int32')

In [7]:
zeroes = np.zeros((2,5))

In [8]:
print(zeroes)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [9]:
a = np.arange(12)

In [10]:
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [11]:
b = np.linspace(1,10,50)

In [12]:
print(b)

[ 1.          1.18367347  1.36734694  1.55102041  1.73469388  1.91836735
  2.10204082  2.28571429  2.46938776  2.65306122  2.83673469  3.02040816
  3.20408163  3.3877551   3.57142857  3.75510204  3.93877551  4.12244898
  4.30612245  4.48979592  4.67346939  4.85714286  5.04081633  5.2244898
  5.40816327  5.59183673  5.7755102   5.95918367  6.14285714  6.32653061
  6.51020408  6.69387755  6.87755102  7.06122449  7.24489796  7.42857143
  7.6122449   7.79591837  7.97959184  8.16326531  8.34693878  8.53061224
  8.71428571  8.89795918  9.08163265  9.26530612  9.44897959  9.63265306
  9.81632653 10.        ]


In [13]:
c = np.empty((4,6))

In [14]:
c

array([[4.67296746e-307, 1.69121096e-306, 1.39071275e-307,
        7.56587584e-307, 1.37961302e-306, 1.05699242e-307],
       [8.01097889e-307, 1.78020169e-306, 7.56601165e-307,
        1.02359984e-306, 1.33510679e-306, 2.22522597e-306],
       [1.33511018e-306, 6.23057689e-307, 1.33511290e-306,
        1.78019082e-306, 8.45559303e-307, 8.06613465e-308],
       [6.89810244e-307, 1.22387550e-307, 2.22522596e-306,
        8.34423917e-308, 9.79107193e-307, 3.33509775e-317]])

In [15]:
dd = np.identity(44)

In [16]:
dd

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [17]:
dd.shape


(44, 44)

In [18]:
ar = np.arange(99)

In [19]:
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [20]:
ar.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [21]:
ar.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [22]:
xy = ([1,2,3],[4,5,6],[7,8,9])

In [23]:
arr = np.array(xy)

In [24]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [25]:
arr.sum(axis = 0)

array([12, 15, 18])

In [26]:
arr.sum(axis = 1)

array([ 6, 15, 24])

In [27]:
arr.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [28]:


arr.flat
for item in arr.flat:
    print(item)
    

1
2
3
4
5
6
7
8
9


In [29]:
arr.ndim

2

In [30]:
arr.size

9

In [31]:
arr.nbytes

36

In [32]:
one = np.array([1,2,3])

In [33]:
one.argmax()

2

In [34]:
one.argmin()

0

In [35]:
one.argsort()

array([0, 1, 2], dtype=int64)

In [36]:
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [37]:
xy


([1, 2, 3], [4, 5, 6], [7, 8, 9])

In [38]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [39]:
arr.argmax()

8

In [40]:
arr.argmin()

0

In [41]:
arr.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]], dtype=int64)

In [42]:
arr.argmin(axis = 0)

array([0, 0, 0], dtype=int64)

In [43]:
xy = ([1,2,3],[4,5,6],[7,8,9])

TypeError: array() takes from 1 to 2 positional arguments but 3 were given

In [45]:
ar2 = np.array(xy)

In [46]:
ar2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [47]:
arr * ar2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [48]:
np.where(arr>5)

(array([1, 2, 2, 2], dtype=int64), array([2, 0, 1, 2], dtype=int64))

In [49]:
type(np.where(arr>5))

tuple

In [50]:
import sys


In [51]:
py_ar = [1,2,3]

In [52]:
np_ar = np.array(py_ar)

In [55]:
sys.getsizeof(1)*len(py_ar())

TypeError: 'list' object is not callable